{% set name = "quasielasticbayes" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../../

build:
  script: {{ PYTHON }} setup.py install
  number: 0

requirements:
  build:
    - {{ compilers }}
  host:
    - python {{ python }}
    - numpy
  run:
    - python {{ python }}
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - quasielasticbayes
  requires:
    - pip
    - pytest
  source_files:
    - quasielasticbayes/test/
  commands:
    - pip check
    - pytest

about:
  home: https://www.mantidproject.org
  summary: A Bayesian fitting package used for fitting quasi-elastic neutron scattering data.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - robertapplin
