name: Build and Test - Python 3.10

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Build Env
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Mambaforge
          environment-file: conda/recipe/qeb-build-py310.yml
          activate-environment: qeb-build-py310
          auto-activate-base: false
      - name: Build
        run: |
          cd conda/recipe
          conda build . --output-folder .
      - name: Setup Test Env
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Mambaforge
          environment-file: conda/recipe/qeb-test-py310.yml
          activate-environment: qeb-test-py310
          auto-activate-base: false
      - name: Install & Test
        run: |
          conda install --force-reinstall --use-local conda/recipe/*-64/quasielasticbayes-0.2.0-*.tar.bz2
          pytest quasielasticbayes/test
