name: Build and Test - Python 3.10

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Activate env
        if: ${{ matrix.os  == 'ubuntu-latest' ||  matrix.os == 'macos-latest'}}
        uses: conda-incubator/setup-miniconda@v3
        with: 
          environment-file: conda_envs/pypi-build-py310.yml
          activate-environment: qeb-pypi-build-py310
      - name: Activate Windows env
        if: ${{ matrix.os  == 'windows-latest'}}
        uses: conda-incubator/setup-miniconda@v3
        with: 
          environment-file: conda_envs/pypi-build-py310-win.yml
          activate-environment: qeb-pypi-build-py310-win
      - name: Build wheel
        run: ./scripts/rebuild.sh
      - name: Install and run tests
        run: |
          pip install --force-reinstall dist/quasielasticbayes-*.whl
          pytest quasielasticbayes/test