name: Build and Test - Python 3.10

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.sys.os }}
    strategy:
      matrix:
        sys: [{ os: ubuntu-latest, shell: 'bash -l {0}'}, 
              {os: macos-latest, shell: 'bash -l {0}'},
              { os: windows-latest, shell: 'cmd {0}'}]
    defaults:
      run:
        shell: ${{ matrix.sys.shell }}

    steps:
      - uses: actions/checkout@v4
      - name: Activate env
        if: ${{ matrix.sys.os  == 'ubuntu-latest' ||  matrix.sys.os == 'macos-latest'}}
        uses: conda-incubator/setup-miniconda@v3
        with: 
          environment-file: conda_envs/pypi-build-py310.yml
          activate-environment: qeb-pypi-build-py310
      - name: Activate Windows env
        if: ${{ matrix.sys.os  == 'windows-latest'}}
        uses: conda-incubator/setup-miniconda@v3
        with: 
          environment-file: conda_envs/pypi-build-py310-win.yml
          activate-environment: qeb-pypi-build-py310-win
      - name: pip install build
        run: pip install build
      - name: Build wheel
        run: python -m build .
      - name: Install and run tests
        run: |
          pip install --force-reinstall dist/quasielasticbayes-*.whl
          pytest src/quasielasticbayes/test