name: Build and Test - Python 3.10

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.sys.os }}
    strategy:
      matrix:
        sys: [{ os: ubuntu-latest, env_name: 'pypi-build-py310-linux'},
              {os: macos-13, env_name: 'pypi-build-py310-macos'},
              {os: macos-latest, env_name: 'pypi-build-py310-macos-arm'},
              { os: windows-latest, env_name: 'pypi-build-py310-windows'}]
      fail-fast: false
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4
      - name: Activate env
        uses: conda-incubator/setup-miniconda@v3
        with: 
          environment-file: conda_envs/${{ matrix.sys.env_name }}.yml
          activate-environment: ${{ matrix.sys.env_name }}
      - name: Meson Build package
        run: |
          export FFLAGS=$(echo $FFLAGS | sed 's/-O2/-O1/' | sed 's/-fstack-protector-strong//')
          meson setup builddir -Dbuildtype=release
          meson compile -C builddir
      - name: Install and run tests
        run: |
          pip install --no-build-isolation -e .
          pytest src/quasielasticbayes/test