name: Windows - Python 3.10

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          miniforge-variant: Mambaforge
          environment-file: qeb-dev-win-py310.yml
          activate-environment: qeb-dev-py310
      - name: Build
        run: |
          python -m pip install -v --editable .
      - name: Test
        run: |
          pytest quasielasticbayes/test
